### ISSUE TITLE
Not tolerant to null object input

### ISSUE THREAD

**Issue by janhoy** [vdmeer/asciitable#14]
Wrote a small program to fill a table from objects. Strings in the objects can be `null`, but then asciitable crashes:

    Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 73, Size: 73
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at de.vandermeer.asciithemes.TA_GridHelpers.adjustBorder(TA_GridHelpers.java:194)
	at de.vandermeer.asciithemes.TA_Grid.addGrid(TA_Grid.java:306)
	at de.vandermeer.asciitable.AT_Renderer.renderAsCollection(AT_Renderer.java:282)
	at de.vandermeer.asciitable.AT_Renderer.render(AT_Renderer.java:128)
	at de.vandermeer.asciitable.AsciiTable.render(AsciiTable.java:191)

I currently work around this in my code with

    at.addRow(Arrays.stream(row).map(v -> v==null?"":v).collect(Collectors.toList()));

**Comment by lorenzo93** [comment]
I started today working with this library and this was my first error. Not good!

Any way to correct this?

**Comment by tholu** [comment]
Same problem here, please fix this!

**Comment by andy176631** [comment]
I think it happened when the value at last column is null, otherwise the cell with null value will merged into its next right cell.

**Comment by tholu** [comment]
@andy176631 That was indeed the case. The pull request should fix this behaviour.

**Comment by PavelTurk** [comment]
@vdmeer Can you say if this project is dead? I don't ask you to do something, please, just answer, it won't take much time.

**Comment by PavelTurk** [comment]
This is not a bug. Null is used as HTML colspan. If you have null in one row, then at least in one row you must have a non null value. Compare:

```
        //this example works
        AsciiTable table = new AsciiTable();
        table.addRule();
        table.addRow("A", null, "B");
        table.addRule();
        table.addRow(1, 2, 3);
        table.addRule();
        System.out.println(table.render());

        //this example doesn't work
        AsciiTable table = new AsciiTable();
        table.addRule();
        table.addRow("A", null, "B");
        table.addRule();
        table.addRow(1, null, 3); // <--  null
        table.addRule();
        System.out.println(table.render());
```
