### ISSUE TITLE
About Java 7 Support

### ISSUE THREAD

**Issue by steelcorsy** [vdmeer/asciitable#37]
I am getting this error:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/builder/ToStringBuilder
	at de.vandermeer.asciitable.v2.row.RuleRow.toString(RuleRow.java:101)
	at de.vandermeer.asciitable.v2.row.RuleRow.toString(RuleRow.java:109)`

I have Commons Lang 2.6, this library requires 3, then, its requiere java 8.
Am I forgetting something?

Thanks.

**Comment by mbigatti** [comment]
Hi @steelcorsy. As I can see from the dependency tree in Maven Repository this version of AsciiTable requires Commons Lang 3. I think there is nothing to do unless the developer release another version with different dependencies.
